/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/objects/manga.glb
Author: Austin Beaulier (https://sketchfab.com/Austin.Beaulier)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/akira-vol-1-photogrammetry-728d17781c464189953e2d9482373b36
Title: Akira vol. 1 (photogrammetry)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/manga.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_2.geometry} material={materials.model_Material_u1_v1} position={[-12.438, 0, -11.185]} rotation={[-Math.PI / 2, 0, 1.19]} />
    </group>
  )
}

useGLTF.preload('/manga.glb')
