/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Kwasson_guy.glb
*/

import React, { useEffect, useRef } from 'react'
import { useAnimations, useFBX, useGLTF } from '@react-three/drei'

export function KwassonGuy(props) {
    const { nodes, materials } = useGLTF('models/Kwasson_guy.glb')
    const group = useRef();

    const { animations: danceAnimation } = useFBX("animations/hip_pop.fbx")
    console.log(danceAnimation);
    danceAnimation[0].name = "dance";
    const { actions } = useAnimations(danceAnimation, group)

    useEffect(() => {
        actions["dance"].reset().play();
    },[])
    return (
        <group {...props} ref={group} dispose={null} rotation-x={-Math.PI / 2} >
      <primitive object={nodes.Hips} />
      <skinnedMesh geometry={nodes.Wolf3D_Body.geometry} material={materials.Wolf3D_Body} skeleton={nodes.Wolf3D_Body.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Bottom.geometry} material={materials.Wolf3D_Outfit_Bottom} skeleton={nodes.Wolf3D_Outfit_Bottom.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Footwear.geometry} material={materials.Wolf3D_Outfit_Footwear} skeleton={nodes.Wolf3D_Outfit_Footwear.skeleton} />
      <skinnedMesh geometry={nodes.Wolf3D_Outfit_Top.geometry} material={materials.Wolf3D_Outfit_Top} skeleton={nodes.Wolf3D_Outfit_Top.skeleton} />
    </group>
    )
}

useGLTF.preload('/Kwasson_guy.glb')
