/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/objects/dumbell.glb
Author: Borrealis (https://sketchfab.com/borrealis)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/metal-dumbell-4f32658bfe5e4455a29b6c9637cbae56
Title: Metal dumbell
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Dumbell(props) {
    const group = useRef();
    const { nodes, materials } = useGLTF('objects/dumbell.glb')
    return (
        <group {...props} ref={group} dispose={null} rotation-y={Math.PI / 2}>
        <group scale={0.005}>
            <mesh geometry={nodes.dumbbell_1_0.geometry} material={materials.material} scale={[205.698, 205.698, 142.103]} />
        </group>
        </group>
    )
}

useGLTF.preload('/dumbell.glb')
