/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/objects/tori.glb
Author: Ash (https://sketchfab.com/ashad.ali.698)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/japanese-gate-a939d00728914dbe80b6ac5fe62966ff
Title: Japanese Gate
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Tori(props) {
    const group = useRef();
  const { nodes, materials } = useGLTF('objects/tori.glb')
  return (
    <group {...props} ref={group} dispose={null} rotation-y={Math.PI / 1}>
      <group position={[9.288, 0, 10.492]} rotation={[0, -0.828, 0]}>
        <mesh geometry={nodes.pasted__pCube59_pasted__lambert5_0.geometry} material={materials.pasted__lambert5} position={[-0.343, 0, -0.315]} />
        <mesh geometry={nodes.pasted__pasted__pCube60_pasted__pasted__lambert6_0.geometry} material={materials.pasted__pasted__lambert6} position={[-7.343, 2.733, -0.149]} scale={[0.317, 0.73, 0.055]} />
      </group>
    </group>
  )
}

useGLTF.preload('/tori.glb')
