/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/altair.glb
Author: milo.melton (https://sketchfab.com/milo.melton)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/assassins-creed-altair-8e84c4d6c628414d90ec2dfb5e19eb6a
Title: Assassins Creed Altair
*/

import React, { useEffect, useRef } from 'react'
import { useAnimations, useFBX, useGLTF } from '@react-three/drei'

export function Altair(props) {
  const { nodes, materials } = useGLTF('models/altair.glb')
  const group = useRef();

    const { animations: danceAnimation } = useFBX("animations/hip_pop.fbx")
    console.log(danceAnimation);
    danceAnimation[0].name = "dance";
    const { actions } = useAnimations(danceAnimation, group)

    useEffect(() => {
        actions["dance"].reset().play();
    },[])
    return (
    <group {...props} ref={group} dispose={null} rotation-x={-Math.PI / 2} scale={0.1}>
      <mesh geometry={nodes.Torso__0.geometry} material={materials.Torso__0} />
      <mesh geometry={nodes.Torso_Hood_0.geometry} material={materials.Hood} />
      <mesh geometry={nodes.Torso_Fingers_0.geometry} material={materials.Fingers} />
      <mesh geometry={nodes.Torso_Sword_0.geometry} material={materials.Sword} />
      <mesh geometry={nodes.Torso_Eyes_0.geometry} material={materials.Eyes} />
      <mesh geometry={nodes.Torso_Shirt_0.geometry} material={materials.Shirt} />
      <mesh geometry={nodes.Torso_Hands_0.geometry} material={materials.Hands} />
      <mesh geometry={nodes.Torso_rai_0.geometry} material={materials.material} />
      <mesh geometry={nodes.Torso_SmallSword_0.geometry} material={materials.SmallSword} />
      <mesh geometry={nodes.Torso_Sword_0_1.geometry} material={materials.Sword} />
      <mesh geometry={nodes.Torso_Shirt_0_1.geometry} material={materials.Shirt} />
      <mesh geometry={nodes.Torso_Boots_0.geometry} material={materials.Boots} position={[0, 0, 0.841]} />
      <mesh geometry={nodes.Torso_Hands_0_1.geometry} material={materials.Hands} />
      <mesh geometry={nodes.Torso_Pants_0.geometry} material={materials.Pants} />
    </group>
  )
}

useGLTF.preload('/altair.glb')
